version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    volumes:
      #volume dos dados
      - dados:/var/lib/postgresql/data
      #scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      #site
      - ./web:/usr/share/nginx/html/
      #configuracao do proxy revers
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80      
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      #aplicacao
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks: 
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    # environment:
    #   - DB_NAME=email_sender
    # ports:
    #     - 8080:8080
  queue:
    image: redis:3.2
    networks: 
      - fila
  worker:
    # image: python:3.6
    build: worker
    volumes:
      #worker
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    # command: bash ./app.sh
    networks:
      - fila
    depends_on:
      - queue